### PR TITLE
Added PressurePipes Support

### PR DESCRIPTION
**Pull request by p-sodmann**
Added Support for Pressure Pipes and recognition of the kind of Tank that is added.
Also simplified the side detection.

https://bdew.net/pressure/tank-data-port/

### CODE REVIEW

**Comment by jaranvil** [comment]
That's awesome. I'll give her a test run later today and merge it with the live code. All running in-game modules will update themselves.

**Comment by p-sodmann** [comment]
If i find the time i will probably add support for the Project Red redstone cables, at least client sided ;)

**Comment by p-sodmann** [comment]
For some reason github behaves strange... you can test my live version with the following installer: http://pastebin.com/Ja5bQSqT

**Comment by jaranvil** [comment]
I installed the module with a OpenBlocks water tank. It updates once, then the program just terminates.  Also, why did you remove computer labeling in your installer?

**Comment by p-sodmann** [comment]
it could be due to that i used the older installer.lua version. i didnt change anything in there though.

havent tried it with OpenBlocks, buildcraft tanks and PressurePipes are working though.
I also included support for multiple tanks but this is rather experimental since the website supports only one tank per computer.

**Comment by jaranvil** [comment]
I'll test it out with some other mods. You might want to grab an updated installer if you want to use your own. 

I can add multiple tank support to the website, also any other modules or updates you're thinking of. I'm much more comfortable on the web side.

**Comment by p-sodmann** [comment]
I just modified the github link for my fluid script in the installer because of more comfort in testing out the script.

I will check out what is going wrong with the OpenBlocks tanks, are there more tanks that should i consider testing?

If i stumble upon things i need for my server, i will add the modules needed like e.g. Railcraft (when i have finally understood it) or ICBM when the development goes on :smile_cat:  

EDIT: The Script works for me, do you have an error message?

**Comment by jaranvil** [comment]
Sorry I'm taking a while to get back to you, been working on another project. I tried it with openBlocks, ender tank, and railcraft iron tank. For all three, on the second loop the program terminates. No errors, just as if the code had completed executing. 

Modules for railcraft and ICBM would be awesome! I'm working on one now for BigReactors. Demethan and I are always on breakfastcraft.com IRC #breakfast, if you ever want to chat there.

**Comment by p-sodmann** [comment]
ohh my mistake, i forgot to mention that i disabled the loop for testing purposes. It is much easier to see if it works if you can reload the file without entering the password over and over again.

i will join you later on irc.

**Comment by jaranvil** [comment]
I copied the code into the dev branch

**Pull request closed without merging**
